# Generated by Django 3.2.9 on 2021-11-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(default='2043392954663228376', max_length=30, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('voter_id', models.CharField(default='9135582136041486756', max_length=30, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_cast', models.DateTimeField(auto_now_add=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vs.candidate')),
                ('voter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vs.voter')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='voter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vs.voter'),
        ),
    ]
