# Generated by Django 3.2.9 on 2021-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(default='1567544489096957534', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(default='9030894600305851197', max_length=30, unique=True),
        ),
    ]
